name: gpf_pyusers
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - python=3.6
  - pip
  - jupyterlab
  - pip:
    - tensorflow>=2.1.0
#    - gpflow==2.0.0
    - git+https://github.com/GPflow/GPflow.git@develop#egg=gpflow


